language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

before_install:
  - pip install pipenv
  - pipenv install
install:
  - python setup.py install

before_script:
  - pip install nose

script:
  - nosetests
